# This is a basic workflow to help you get started with Actions

name: Slack Notifications

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ onboarding ]
  pull_request:
    branches: [ onboarding ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  notifySlack:
  
  runs-on: ubuntu-latest
  
  steps:
  - name: Notify Slack
  env:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  uses: abinoda/slack-action@master
  with:
  #https://app.slack.com/client/T023L1ERXKR/C0240Q0HACA
    args: '{\"channel\":\"C0240Q0HACA\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* ${{ github.event.pull_request.title }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Who?:* ${{ github.event.pull_request.user.login }}\n*Request State:* ${{ github.event.pull_request.state }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.pull_request.html_url }}|View Pull Request>\"}}]}'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
